/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProcessingRouteImport } from './routes/processing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AskRouteImport } from './routes/ask'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReviewJobIdRouteImport } from './routes/review.$jobId'
import { Route as ReportPrintRouteImport } from './routes/report.print'
import { Route as ReportWeekStartRouteImport } from './routes/report.$weekStart'
import { Route as DataWeekStartRouteImport } from './routes/data.$weekStart'

const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessingRoute = ProcessingRouteImport.update({
  id: '/processing',
  path: '/processing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AskRoute = AskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewJobIdRoute = ReviewJobIdRouteImport.update({
  id: '/review/$jobId',
  path: '/review/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportPrintRoute = ReportPrintRouteImport.update({
  id: '/report/print',
  path: '/report/print',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportWeekStartRoute = ReportWeekStartRouteImport.update({
  id: '/report/$weekStart',
  path: '/report/$weekStart',
  getParentRoute: () => rootRouteImport,
} as any)
const DataWeekStartRoute = DataWeekStartRouteImport.update({
  id: '/data/$weekStart',
  path: '/data/$weekStart',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/processing': typeof ProcessingRoute
  '/register': typeof RegisterRoute
  '/upload': typeof UploadRoute
  '/data/$weekStart': typeof DataWeekStartRoute
  '/report/$weekStart': typeof ReportWeekStartRoute
  '/report/print': typeof ReportPrintRoute
  '/review/$jobId': typeof ReviewJobIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/processing': typeof ProcessingRoute
  '/register': typeof RegisterRoute
  '/upload': typeof UploadRoute
  '/data/$weekStart': typeof DataWeekStartRoute
  '/report/$weekStart': typeof ReportWeekStartRoute
  '/report/print': typeof ReportPrintRoute
  '/review/$jobId': typeof ReviewJobIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/processing': typeof ProcessingRoute
  '/register': typeof RegisterRoute
  '/upload': typeof UploadRoute
  '/data/$weekStart': typeof DataWeekStartRoute
  '/report/$weekStart': typeof ReportWeekStartRoute
  '/report/print': typeof ReportPrintRoute
  '/review/$jobId': typeof ReviewJobIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ask'
    | '/dashboard'
    | '/history'
    | '/login'
    | '/processing'
    | '/register'
    | '/upload'
    | '/data/$weekStart'
    | '/report/$weekStart'
    | '/report/print'
    | '/review/$jobId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ask'
    | '/dashboard'
    | '/history'
    | '/login'
    | '/processing'
    | '/register'
    | '/upload'
    | '/data/$weekStart'
    | '/report/$weekStart'
    | '/report/print'
    | '/review/$jobId'
  id:
    | '__root__'
    | '/'
    | '/ask'
    | '/dashboard'
    | '/history'
    | '/login'
    | '/processing'
    | '/register'
    | '/upload'
    | '/data/$weekStart'
    | '/report/$weekStart'
    | '/report/print'
    | '/review/$jobId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AskRoute: typeof AskRoute
  DashboardRoute: typeof DashboardRoute
  HistoryRoute: typeof HistoryRoute
  LoginRoute: typeof LoginRoute
  ProcessingRoute: typeof ProcessingRoute
  RegisterRoute: typeof RegisterRoute
  UploadRoute: typeof UploadRoute
  DataWeekStartRoute: typeof DataWeekStartRoute
  ReportWeekStartRoute: typeof ReportWeekStartRoute
  ReportPrintRoute: typeof ReportPrintRoute
  ReviewJobIdRoute: typeof ReviewJobIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/processing': {
      id: '/processing'
      path: '/processing'
      fullPath: '/processing'
      preLoaderRoute: typeof ProcessingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ask': {
      id: '/ask'
      path: '/ask'
      fullPath: '/ask'
      preLoaderRoute: typeof AskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review/$jobId': {
      id: '/review/$jobId'
      path: '/review/$jobId'
      fullPath: '/review/$jobId'
      preLoaderRoute: typeof ReviewJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report/print': {
      id: '/report/print'
      path: '/report/print'
      fullPath: '/report/print'
      preLoaderRoute: typeof ReportPrintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report/$weekStart': {
      id: '/report/$weekStart'
      path: '/report/$weekStart'
      fullPath: '/report/$weekStart'
      preLoaderRoute: typeof ReportWeekStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data/$weekStart': {
      id: '/data/$weekStart'
      path: '/data/$weekStart'
      fullPath: '/data/$weekStart'
      preLoaderRoute: typeof DataWeekStartRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AskRoute: AskRoute,
  DashboardRoute: DashboardRoute,
  HistoryRoute: HistoryRoute,
  LoginRoute: LoginRoute,
  ProcessingRoute: ProcessingRoute,
  RegisterRoute: RegisterRoute,
  UploadRoute: UploadRoute,
  DataWeekStartRoute: DataWeekStartRoute,
  ReportWeekStartRoute: ReportWeekStartRoute,
  ReportPrintRoute: ReportPrintRoute,
  ReviewJobIdRoute: ReviewJobIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
